version: "3.8"
services:
  # mongodb database
  mongodb:
    image: mongo
    container_name: mash-mongo
    restart: unless-stopped
    env_file: ./.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGODB_USER
      MONGO_INITDB_ROOT_PASSWORD: $MONGODB_PASSWORD
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
    volumes:
      - db:/data/db
    command: mongod --quiet
    # networks:
    #   - admin
    #   - frontend
  
  # mongo-express admin interface for mongodb
  mongo-admin:
    image: mongo-express
    container_name: mash-mongo-admin
    restart: unless-stopped
    depends_on:
      - mongodb
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: $MONGODB_DOCKER_PORT
      ME_CONFIG_MONGODB_ADMINUSERNAME: $MONGODB_USER
      ME_CONFIG_MONGODB_ADMINPASSWORD: $MONGODB_PASSWORD
      ME_CONFIG_BASICAUTH_USERNAME: $ADMIN_USER
      ME_CONFIG_BASICAUTH_PASSWORD: $ADMIN_PASSWORD
      VCAP_APP_PORT: $ADMIN_DOCKER_PORT
    ports:
      - $ADMIN_LOCAL_PORT:$ADMIN_DOCKER_PORT
    # networks:
    #   - admin
  
  # mash server
  mash:
    container_name: mash-server
    depends_on:
      - mongodb
    build: ./
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $MASH_LOCAL_PORT:$MASH_DOCKER_PORT
    environment:
      DB_HOST: mongodb
      DB_USER: $MONGODB_USER
      DB_PASSWORD: $MONGODB_PASSWORD
      DB_NAME: $MONGODB_DATABASE
      DB_PORT: $MONGODB_DOCKER_PORT
      MASH_API_BASE_PATH: $MASH_API_BASE_PATH
      MASH_FRONTEND_BASE_PATH: $MASH_FRONTEND_BASE_PATH
      MASH_PORT: $MASH_DOCKER_PORT

  tor:
    container_name: mash-hidden-service
    image: goldy/tor-hidden-service:latest
    environment:
        SERVICE1_TOR_SERVICE_HOSTS: $MASH_HIDDEN_SERVICE_PORT:mash:$MASH_DOCKER_PORT
        # tor v3 address private key base 64 encoded
        SERVICE1_TOR_SERVICE_KEY: $MASH_HIDDEN_SERVICE_KEY
    # networks:
    #   - frontend

# networks:
#   frontend:
#     driver: bridge
#   admin:

volumes:
  db:
